name: Update WordPress.org assets

on:
    push:
        branches: [main]
        paths:
            - .wordpress-org/**
            - readme.txt
    workflow_dispatch:

concurrency:
    group: wordpress-org
    cancel-in-progress: false

permissions:
    contents: read

jobs:
    assets:
        name: Update assets & readme
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Update WordPress.org assets
              uses: 10up/action-wordpress-plugin-asset-update@stable
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: gpx-route-map
